#!/bin/sh

INITSCRIPTS_DIR=/etc/modules-helpers

case $1 in
    start)
        $INITSCRIPTS_DIR/scull_load
        $INITSCRIPTS_DIR/module_load faulty
        $INITSCRIPTS_DIR/aesdchar_load
    ;;
    stop)
        $INITSCRIPTS_DIR/scull_unload
        $INITSCRIPTS_DIR/module_unload faulty
        $INITSCRIPTS_DIR/aesdchar_unload
    ;;
esac